Hw2305
alexnigma/mocha pull request #3
Opened 2023-05-22 22:45 UTC by alexnigma

2023-05-23 08:50 UTC, SanitarskyiDmytro requested changes

2023-05-23 08:50 UTC, SanitarskyiDmytro commented on cypress/e2e/hw2305.spec.cy.js
> +            cy.get(`nb-toastr-container.ng-tns-c209-54 > .ng-tns-c209-54`).invoke(`prop`, `offsetTop`).should(`eq`, Number(`${expectedPositionTop}`))
спробуйте змінити розширення екрану і перевірте чи буде працювати ця перевірка. 

Щоб не було залежності від координат, пошукайте в кожного тоста батьківський контейнер, там можна знайти параметри що відповідають за позицію

2023-05-29 17:48 UTC, alexnigma commented on cypress/e2e/hw2305.spec.cy.js
> +            cy.get(`nb-toastr-container.ng-tns-c209-54 > .ng-tns-c209-54`).invoke(`prop`, `offsetTop`).should(`eq`, Number(`${expectedPositionTop}`))
Fixed.
Please check.

2023-05-30 08:50 UTC, SanitarskyiDmytro approved these changes

2023-05-30 09:19 UTC, merged